package iuh.fit.core.net.protocol;

public enum CommandAction {
    AUTH_LOGIN,
    AUTH_LOGOUT,
    PING,

    // ===== Hóa đơn (read-only) =====
    HOADON_GET_BY_PAGE,
    HOADON_GET_TOTAL,
    HOADON_GET_DETAIL,

    // ===== Dashboard (read) =====
    DASHBOARD_DAILY_REVENUE,
    DASHBOARD_TOP_SELLING,
    DASHBOARD_LEAST_SELLING,
    DASHBOARD_TABLE_STATUS_COUNTS,

    // ===== Phase 3 (write features) - skeleton =====
    PHANCONG_ADD,
    PHANCONG_REMOVE,
    PHANCONG_LIST_BY_DATE,
    PHANCONG_GET_BY_DATE_RANGE,
    PHANCONG_GET_TONG_GIO_THEO_THANG,

    // ===== Nhân viên =====
    NHANVIEN_GET_ALL,
    NHANVIEN_GET_BY_ID,
    NHANVIEN_ADD,
    NHANVIEN_UPDATE,
    NHANVIEN_TOGGLE_STATUS,
    NHANVIEN_GET_EMAIL_BY_TENTK,
    NHANVIEN_GET_ACCOUNT_STATUS,

    BAN_GET_ALL,
    BAN_UPDATE_STATUS,
    BAN_CHUYEN_BAN,
    BAN_GHEP_BAN,

    // ===== Khách hàng =====
    KHACHHANG_GET_ALL,
    KHACHHANG_GET_BY_ID,
    KHACHHANG_GET_BY_SDT,
    KHACHHANG_ADD,
    KHACHHANG_UPDATE,
    KHACHHANG_SEARCH,

    // ===== Khuyến mãi =====
    KHUYENMAI_GET_ALL,
    KHUYENMAI_GET_BY_ID,
    KHUYENMAI_ADD,
    KHUYENMAI_UPDATE,
    KHUYENMAI_DELETE,
    KHUYENMAI_USE,

    // ===== Danh mục món / Món ăn (admin) =====
    DANHMUCMON_GET_ALL,
    DANHMUCMON_ADD,
    DANHMUCMON_UPDATE,
    DANHMUCMON_DELETE,
    MONAN_ADMIN_GET_ALL,
    MONAN_ADMIN_GET_BY_ID,
    MONAN_ADMIN_ADD,
    MONAN_ADMIN_UPDATE,
    MONAN_ADMIN_UPDATE_STATUS,

    // ===== Tài khoản =====
    TAIKHOAN_UPDATE_PASSWORD,

    // ===== Ca làm =====
    CALAM_GET_ALL_ORDER_BY_START,
    GIAOCA_DASHBOARD_LOAD,
    GIAOCA_START,
    GIAOCA_END,
    GIAOCA_GET_LICH_SU,
    GIAOCA_GET_ACTIVE_STAFF,
    GIAOCA_GET_TOP_STAFF_HOURS,

    DONDATMON_GET_ALL_CHUA_NHAN,
    DONDATMON_SEARCH_CHUA_NHAN,
    DONDATMON_GET_BAN_DA_DAT_TRONG_KHOANG,
    DONDATMON_SAVE,
    DONDATMON_HUY_DAT_BAN,
    DONDATMON_GET_BY_ID,

    // ===== Gọi món / mở bàn =====
    MONAN_GET_ALL,

    HOADON_GET_CHUA_THANH_TOAN_BY_BAN,
    HOADON_MO_BAN_TAO_HOA_DON,
    HOADON_CAP_NHAT_TONG_TIEN,

    CHITIETHOADON_GET_BY_MA_DON,
    CHITIETHOADON_REPLACE_BY_MA_DON,

    DONDATMON_GET_DAT_TRUOC_BY_BAN,
    DONDATMON_GET_CHUA_NHAN_THEO_BAN_BAO_GOM_LINKED,
    DONDATMON_GET_ALL_CHUA_NHAN_BAO_GOM_LINKED,
    
    HOADON_THANH_TOAN,
    HOADON_CAP_NHAT_MA_KM,
    HOADON_CAP_NHAT_MA_KH,
    HOADON_TINH_LAI_GIAM_GIA_VA_TONG_TIEN,

    CHITIETHOADON_ADD,
    CHITIETHOADON_UPDATE,
    CHITIETHOADON_DELETE
}
